#!/usr/bin/env python3
"""Emit `OpenImagesV7Mapping.swift` from Ultralytics OIV7 weights (601 classes, index-aligned).

Run from repo root after weights exist: `python3 scripts/gen_open_images_v7_mapping.py`
Default source: `yolov8m-oiv7.pt` (downloaded by Ultralytics on first use).
"""

from __future__ import annotations

import argparse
from pathlib import Path

from ultralytics import YOLO

REPO = Path(__file__).resolve().parents[1]
DEFAULT_PT = REPO / "yolov8m-oiv7.pt"
OUT = REPO / "ios" / "VisionBridgeKit" / "Sources" / "VisionBridgeKit" / "OpenImagesV7Mapping.swift"


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument(
        "--pt",
        type=Path,
        default=DEFAULT_PT,
        help="Path to .pt (or model name like yolov8m-oiv7.pt for auto-download)",
    )
    p.add_argument("--out", type=Path, default=OUT)
    args = p.parse_args()

    model = YOLO(str(args.pt))
    n = len(model.names)
    lines = [
        "// Generated by scripts/gen_open_images_v7_mapping.py — do not edit by hand.",
        "// Class index matches Ultralytics YOLOv8 *-oiv7 detection heads (Open Images V7).",
        "",
        "import Foundation",
        "",
        "/// Open Images V7 class index → name for Vision numeric labels (`\"0\"`, `\"1\"`, …).",
        "enum OpenImagesV7Mapping {",
        "    static let classNames: [String] = [",
    ]
    for i in range(n):
        raw = str(model.names[i])
        escaped = raw.replace("\\", "\\\\").replace('"', '\\"')
        comma = "," if i < n - 1 else ""
        lines.append(f'        "{escaped}"{comma}')
    lines.append("    ]")
    lines.append("}")
    lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {n} classes to {args.out}")


if __name__ == "__main__":
    main()
